module.exports = {
    "id": 11,
    "apiUrl": null,
    "reportName": "Quotation Register",
    "spName": "quotationRegister",
    "groupingDepth": null,
    "sorting": "y",
    "fields": [
        {
            "id": 4,
            "fieldname": null,
            "controlname": 6652,
            "controlDefaultValue": null,
            "dropdownFilter": null,
            "dropDownValues": null,
            "functionOnBlur": null,
            "functionOnChange": null,
            "functionOnKeyPress": null,
            "isControlShow": true,
            "isEditable": true,
            "isRequired": false,
            "referenceColumn": "name",
            "referenceTable": "tblCompany",
            "toolTipMessage": "Customer",
            "type": 6653,
            "yourlabel": "Customer",
            "ordering": 1
        },
        {
            "id": 6,
            "fieldname": null,
            "controlname": 6652,
            "controlDefaultValue": null,
            "dropdownFilter": null,
            "dropDownValues": null,
            "functionOnBlur": null,
            "functionOnChange": null,
            "functionOnKeyPress": null,
            "isControlShow": true,
            "isEditable": true,
            "isRequired": false,
            "referenceColumn": "name",
            "referenceTable": "tblPort",
            "toolTipMessage": "POL",
            "type": 6653,
            "yourlabel": "POL",
            "ordering": 4
        },
        {
            "id": 7,
            "fieldname": null,
            "controlname": 6652,
            "controlDefaultValue": null,
            "dropdownFilter": null,
            "dropDownValues": null,
            "functionOnBlur": null,
            "functionOnChange": null,
            "functionOnKeyPress": null,
            "isControlShow": true,
            "isEditable": true,
            "isRequired": false,
            "referenceColumn": "name",
            "referenceTable": "tblPort",
            "toolTipMessage": "POD",
            "type": 6653,
            "yourlabel": "POD",
            "ordering": 5
        },
        {
            "id": 8,
            "fieldname": "fromDate",
            "controlname": 6571,
            "controlDefaultValue": null,
            "dropdownFilter": null,
            "dropDownValues": null,
            "functionOnBlur": null,
            "functionOnChange": null,
            "functionOnKeyPress": null,
            "isControlShow": true,
            "isEditable": true,
            "isRequired": false,
            "referenceColumn": null,
            "referenceTable": null,
            "toolTipMessage": "From Date",
            "type": 6783,
            "yourlabel": "From Date",
            "ordering": 6
        },
        {
            "id": 9,
            "fieldname": "toDate",
            "controlname": 6571,
            "controlDefaultValue": null,
            "dropdownFilter": null,
            "dropDownValues": null,
            "functionOnBlur": null,
            "functionOnChange": null,
            "functionOnKeyPress": null,
            "isControlShow": true,
            "isEditable": true,
            "isRequired": false,
            "referenceColumn": null,
            "referenceTable": null,
            "toolTipMessage": "To Date",
            "type": 6783,
            "yourlabel": "To Date",
            "ordering": 7
        }
    ],
    "grid": [
        {
            "fieldname": "Quotation Date",
            "controlname": "date",
            "referenceColumn": "quotationNo",
            "referenceTable": "tblQuotation",
            "isControlShow": true,
            "isEditable": true,
            "isRequired": false,
            "yourlabel": "Quotation Date",
        },
        {
            "fieldname": "Customer",
            "controlname": "dropdown",
            "referenceColumn": "name",
            "referenceTable": "tblCompany",
            // "dropdownFilter": null,
            // "dropDownValues": null,
            // "functionOnBlur": null,
            // "functionOnChange": null,
            // "functionOnKeyPress": null,
            "isControlShow": true,
            "isEditable": true,
            "isRequired": false,
            "toolTipMessage": "",
            "type": 6653,
            "yourlabel": "Customer",
            "ordering": 4
        }
    ],
    "buttons": [
        {
            "id": 4,
            "buttonName": "Go",
            "iconName": null,
            "ordering": 1,
            "functionOnClick": "handleSubmit"
        },
        {
            "id": 5,
            "buttonName": "Export to Excel",
            "iconName": null,
            "ordering": 2,
            "functionOnClick": "handleExportToExcel"
        },
        {
            "id": 6,
            "buttonName": "Export to Excel (Data Only)",
            "iconName": null,
            "ordering": 3,
            "functionOnClick": "handleExportToExcelDataOnly"
        },
        {
            "id": 7,
            "buttonName": "Export to CSV",
            "iconName": null,
            "ordering": 4,
            "functionOnClick": "handleExportToCSV"
        },
        {
            "id": 8,
            "buttonName": "Print",
            "iconName": null,
            "ordering": 5,
            "functionOnClick": "handlePrint"
        }
    ]
}