export const CHAT_DATA = [
        {
            id: 1,
            name: "Priya Sharma",
            initials: "PS",
            colorClass: "bg-teal-100 text-teal-800",
            status: "online",
            lastSeen: "online",
            unread: 3,
            muted: false,
            isGroup: false,
            messages: [
                { id: 1, from: "them", text: "Hey! Are you free for the design review today?", time: "10:12 AM", date: "Today" },
                { id: 2, from: "me", text: "Yes, what time works for you?", time: "10:14 AM", date: "Today" },
                { id: 3, from: "them", text: "Let's do 3pm? I'll share the Figma link", time: "10:16 AM", date: "Today" },
                { id: 4, from: "me", text: "Perfect! I'll prepare my notes", time: "10:17 AM", date: "Today" },
                { id: 5, from: "them", text: "Also, did you check the latest prototype I sent?", time: "10:32 AM", date: "Today" },
                { id: 6, from: "them", text: "The new onboarding flow looks much better now 🎉", time: "10:33 AM", date: "Today" },
                { id: 7, from: "them", text: "Let me know what you think!", time: "10:33 AM", date: "Today" },
            ],
        },
        {
            id: 2,
            name: "Dev Team 🚀",
            initials: "DT",
            colorClass: "bg-blue-100 text-blue-800",
            status: "away",
            lastSeen: "2 members online",
            unread: 0,
            muted: true,
            isGroup: true,
            messages: [
                { id: 1, from: "them", text: "Build #142 deployed to staging ✅", time: "9:00 AM", date: "Today" },
                { id: 2, from: "me", text: "Nice! I'll start QA testing now", time: "9:04 AM", date: "Today" },
                { id: 3, from: "them", text: "Found a regression on the payment flow 🐛", time: "9:45 AM", date: "Today" },
                { id: 4, from: "them", text: "PR #389 is up for review", time: "10:01 AM", date: "Today" },
            ],
        },
        {
            id: 3,
            name: "Arjun Mehta",
            initials: "AM",
            colorClass: "bg-orange-100 text-orange-800",
            status: "offline",
            lastSeen: "last seen 2h ago",
            unread: 1,
            muted: false,
            isGroup: false,
            messages: [
                { id: 1, from: "them", text: "Are the API docs updated yet?", time: "Yesterday", date: "Yesterday" },
                { id: 2, from: "me", text: "Almost done, will push by EOD", time: "Yesterday", date: "Yesterday" },
                { id: 3, from: "them", text: "Thanks! Let me know once it's live", time: "Yesterday", date: "Yesterday" },
                { id: 4, from: "them", text: "Also, should we migrate to the new endpoint?", time: "8:50 AM", date: "Today" },
            ],
        },
        {
            id: 4,
            name: "Meera Nair",
            initials: "MN",
            colorClass: "bg-pink-100 text-pink-800",
            status: "online",
            lastSeen: "online",
            unread: 0,
            muted: false,
            isGroup: false,
            messages: [
                { id: 1, from: "me", text: "Hey Meera, sent the report over email 📊", time: "Yesterday", date: "Yesterday" },
                { id: 2, from: "them", text: "Got it! Great work on the Q2 summary", time: "Yesterday", date: "Yesterday" },
                { id: 3, from: "them", text: "Can we schedule a sync for Monday?", time: "Yesterday", date: "Yesterday" },
            ],
        },
        {
            id: 5,
            name: "Product Guild",
            initials: "PG",
            colorClass: "bg-green-100 text-green-800",
            status: "away",
            lastSeen: "5 members online",
            unread: 7,
            muted: false,
            isGroup: true,
            messages: [
                { id: 1, from: "them", text: "Roadmap planning session — Tue 4pm", time: "Mon", date: "Monday" },
                { id: 2, from: "them", text: "Please review the PRD before then 📋", time: "Mon", date: "Monday" },
                { id: 3, from: "me", text: "On it, thanks for the reminder", time: "Mon", date: "Monday" },
                { id: 4, from: "them", text: "Don't forget the competitive analysis slides!", time: "9:30 AM", date: "Today" },
            ],
        },
        {
            id: 6,
            name: "Rahul Joshi",
            initials: "RJ",
            colorClass: "bg-amber-100 text-amber-800",
            status: "offline",
            lastSeen: "last seen yesterday",
            unread: 0,
            muted: false,
            isGroup: false,
            messages: [
                { id: 1, from: "them", text: "Coffee tomorrow?", time: "Tue", date: "Tuesday" },
                { id: 2, from: "me", text: "Sure! 10am at the usual place 😊", time: "Tue", date: "Tuesday" },
            ],
        },
        {
            id: 7,
            name: "Sneha Pillai",
            initials: "SP",
            colorClass: "bg-gray-100 text-gray-700",
            status: "online",
            lastSeen: "online",
            unread: 0,
            muted: true,
            isGroup: false,
            messages: [
                { id: 1, from: "them", text: "Can you review my portfolio?", time: "Mon", date: "Monday" },
                { id: 2, from: "me", text: "Yes! Send me the link when ready", time: "Mon", date: "Monday" },
            ],
        },
    ];
